# Generated by Django 4.2.6 on 2023-10-15 19:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("datetime", models.DateTimeField(blank=True, null=True)),
                ("thumb_image", models.ImageField(null=True, upload_to="Event/")),
                (
                    "encryption_code",
                    models.CharField(
                        default=b"kFA0uDuo2O543cKstmQTorZp_egEcazpMCdkGwX-nP8=",
                        editable=False,
                        max_length=400,
                    ),
                ),
            ],
        ),
    ]
