# Generated by Django 4.2.7 on 2023-11-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("steps", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="encryption_code",
            field=models.CharField(
                default=b"YMhZQpH3mQ_3Ita4i7ODp1DhH84e5HxjEnCXGBBjjwQ=",
                editable=False,
                max_length=400,
            ),
        ),
    ]
